apiVersion: v1
kind: Pod
metadata:
  name: py-etl-host-network-pod
  namespace: default
spec:
  hostNetwork: true
  dnsPolicy: Default
  containers:
  - name: py-etl-test
    image: brentgroves/py-etl-training:7
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always  

