kind: "Service"
apiVersion: "v1"
metadata:
  name: "busche-sql-svc"
spec:
  ports:
    -
      name: "busche-sql-port"
      protocol: "TCP"
      port: 1433
      targetPort: 1433 
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "busche-sql-svc" 
subsets: 
  -
    addresses:
      -
        ip: "10.1.2.74" #The IP Address of the busche-sql
    ports:
      -
        port: 1433 
        name: "busche-sql-port"
