apiVersion: v1
kind: Service
metadata:
  name: buschesql
spec:
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Endpoints
metadata:
  name: buschesql
subsets:
  - addresses:
      - ip: 10.1.2.74
    ports:
      - port: 1433